<input id="pareto-tab-1" type="radio" name="pareto-tab__item" checked>
<label for="pareto-list__1m" class="pareto-tab__item">for 1 month</label>
<input id="pareto-tab-3" type="radio" name="pareto-tab__item">
<label for="pareto-list__3m" class="pareto__tab__item">for 3 month</label>
<!--<input id="pareto-tab-3" type="radio" name="pareto__tab__item">-->
<!--<label for="pareto-list__6m" class="pareto__tab__item">for 6 month</label>-->
