<input id="pareto-tab-1" type="radio" name="pareto-tab__item" checked>
<label for="pareto-tab-1" class="pareto-tab__item">1 month</label>
<input id="pareto-tab-3" type="radio" name="pareto-tab__item">
<label for="pareto-tab-3" class="pareto-tab__item">3 month</label>
<!--<input id="pareto-tab-3" type="radio" name="pareto__tab__item">-->
<!--<label for="pareto-list__6m" class="pareto__tab__item">6 month</label>-->
